name: Auto publish

on:
  push:
    paths:
      - 'info.json' # Triggers only if the mod info file is updated
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'version'
    - name: get factorio_version
      id: factorio_version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'factorio_version'
    - name: get mod name
      id: mod_name
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'name'
    - name: Zip mod
      run: bash ./.scripts/zip_mod.sh
    - uses: marvinpinto/action-automatic-releases@latest
      id: aar
      with:
        automatic_release_tag: "${{steps.version.outputs.prop}}"
        title: "For factorio ${{steps.factorio_version.outputs.prop}}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip
    - uses: TGNThump/factorio-publish-mod-action@v1
      with:
        mod_portal_username: ${{ secrets.FACTORIO_USER }}
        mod_portal_password: ${{ secrets.FACTORIO_PASSWORD }}
        mod_name: ${{steps.mod_name.outputs.prop}}
        asset_path: ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip
        asset_name: ${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip