on:
  push:
    branches:
      - main

name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Publish Mod
      uses: shanemadden/factorio-mod-portal-publish@stable
      env:
        FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}
        FACTORIO_USER: ${{ secrets.FACTORIO_USER }}
